[package]
name = "rust_in_action"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.131"
piston2d-graphics = "0.44"
rand = "0.8.5"
